const MAX_INTEGER_DIGITS = 11
const MAX_DECIMAL_INTEGER_DIGITS = 10
const MAX_DECIMAL_FRACTION_DIGITS = 6

export {
    MAX_INTEGER_DIGITS,
    MAX_DECIMAL_INTEGER_DIGITS,
    MAX_DECIMAL_FRACTION_DIGITS
}
